export const START_AUTH = "START_AUTH"
export const END_OF_AUTH = "END_OF_AUTH"
export const AUTH_ERROR = "AUTH_ERROR"
export const SUCCESSFUL_AUTH = "SUCCESSFUL_AUTH"
export const LOG_OUT = "LOG_OUT"